apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: swagger
  name: swagger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: swagger
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: swagger
    spec:
      containers:
        - env:
            - name: LAYOUT
              value: BaseLayout
            - name: SWAGGER_JSON
              value: /home/swagger.json
          image: swaggerapi/swagger-ui:v4.6.1
          name: swagger
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /home
              name: swagger-volume
      restartPolicy: Always
      volumes:
        - name: swagger-volume
          configMap:
            name: swagger
status: {}
