apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: nginx
    protocol: TCP
    port: 4430
    targetPort: 8080
    nodePort: 31592
  type: NodePort
  selector:
    app: nginx