apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim1
  labels:
    app: nginx-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
