apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
   app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.18.0
          name: nginx
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /certs
              name: nginx-claim0
            - mountPath: /config/nginx.conf
              name: nginx-claim1
      volumes:
        - name: nginx-claim0
          persistentVolumeClaim:
            claimName: nginx-claim0
        - name: nginx-claim1
          persistentVolumeClaim:
            claimName: nginx-claim1
status: {}
