apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nginx-rootca
data:
  rootCA.crt: |
    -----BEGIN CERTIFICATE-----
    MIID2zCCAsOgAwIBAgIUPIJHcw4Mt0KRNUKwyF4VnYvtcKMwDQYJKoZIhvcNAQEL
    BQAwfTELMAkGA1UEBhMCRVMxETAPBgNVBAgMCEdpcHV6a29hMQswCQYDVQQHDAJT
    UzENMAsGA1UECgwEQ0VJVDENMAsGA1UECwwEREFJTTEOMAwGA1UEAwwFaWMybTIx
    IDAeBgkqhkiG9w0BCQEWEXNmaWd1ZXJvYUBjZWl0LmVzMB4XDTIzMDQxOTIwMDkw
    MFoXDTI1MDQxODIwMDkwMFowfTELMAkGA1UEBhMCRVMxETAPBgNVBAgMCEdpcHV6
    a29hMQswCQYDVQQHDAJTUzENMAsGA1UECgwEQ0VJVDENMAsGA1UECwwEREFJTTEO
    MAwGA1UEAwwFaWMybTIxIDAeBgkqhkiG9w0BCQEWEXNmaWd1ZXJvYUBjZWl0LmVz
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1ZDOWRDOBBbjMrRfhMRI
    JXJT8fytygUwdmbnSrG/qc2YzIcNpy6DM0itl60+N8lZ1Eo/ktE6oCOgCDpckxUM
    wqMoDIiF6tErJW7gChjv8hGz/wnbuY1RFo41lEoE6BQV7Ghz2o38EtywMPRvthpQ
    zQoan3HW2ozptgduL20qIQItqjG75fZeCMc5rtS5GGtyc9JGntgkZuY5NHu0BqEf
    s7NzQ3ETGCqmVnPx4gLgwH7ifJFzHRQZme5/7SVUaHAKMBNc7OVQ41Ww6PzFa/h5
    GWGMr5N05M8D/8+TZn3qjozEnoIPhf+WVCXHxgWBPI15XaBgVMaPyTCipywB+g7h
    QQIDAQABo1MwUTAdBgNVHQ4EFgQUhwN2BEEKQC4nICO9KRbi6ZKfFjswHwYDVR0j
    BBgwFoAUhwN2BEEKQC4nICO9KRbi6ZKfFjswDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAg6o4NImHRl/ynTSiiI72CezIMIFzB968tXahBt9kA6Ct
    a1mdBo6BYBgpeBa5IEzIYaNuCffDQiMw+QzK4Cd4IbUfJtnPTG5A/SRizxEctgDf
    Nt5fefArSb6qGNVhSvMfAlwdef40eNEQu+VTWwN63ZZhNb7PKOWlAkOpfGPtDGYB
    +s/RT1EZMH/J4flvGWVOavD1BymYVu5sNg2El/5FTSAw9Y9Cckz3/pCb0NwkS2JP
    5FtSVnhZTBUHmJKp1n23i5exZNSOBGUyXXxiRPCr7gwW5ZaV9HdHwO13PJOZ4dV3
    IOy7C4zp+lwYjqUvfwooKVKWVeUVW6OozKh7t151yA==
    -----END CERTIFICATE-----

