apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.18.0
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
        - containerPort: 4430
        volumeMounts:
        - name: configmap-nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: configmap-nginx-crt
          mountPath: /etc/nginx/ssl/crt
        - name: configmap-nginx-key
          mountPath: /etc/nginx/ssl/key
        - name: configmap-nginx-dh
          mountPath: /etc/nginx/ssl
        - name: configmap-nginx-rootca
          mountPath: /etc/nginx/ssl/rootca
      # Load the configuration files for nginx
      volumes:
        - name: configmap-nginx-conf
          configMap:
            name: configmap-nginx-conf
        - name: configmap-nginx-dh
          configMap:
            name: configmap-nginx-dh
        - name: configmap-nginx-crt
          configMap:
            name: configmap-nginx-crt
        - name: configmap-nginx-key
          configMap:
            name: configmap-nginx-key
        - name: configmap-nginx-rootca
          configMap:
            name: configmap-nginx-rootca